import mock from '../mock';
import { sub } from 'date-fns';
import { Chance } from 'chance';

const chance = new Chance();

const ProductsDatav2 = [
  {
    title: 'Cetaphil Cleanser Skin',
    price: 16.25,
    discount: 25,
    related: false,
    salesPrice: 24.25,
    category: ['books'],
    gender: 'Men',
    rating: 4.8,
    stock: true,
    qty: 1,
    colors: ['#1890FF'],
    photo: "/images/products/product-10.jpg",
    id: 1,
    created: sub(new Date(), { days: 8, hours: 6, minutes: 20 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'Kiehl Ultra Facial Cleanser',
    price: 12.21,
    discount: 10,
    related: true,
    salesPrice: 13.50,
    category: ['books'],
    gender: 'Women',
    rating: 3,
    stock: false,
    qty: 1,
    colors: ['#1890FF', '#94D82D', '#FF4842'],
    photo: "/images/products/product-11.jpg",
    id: 2,
    created: sub(new Date(), { days: 10, hours: 8, minutes: 69 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'Dermalogica Cleansing Gel',
    price: 85.00,
    discount: 12,
    related: false,
    salesPrice: 90.25,
    category: ['fashion', 'books'],
    gender: 'Kids',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#FF4842', '#1890FF', '#94D82D'],
    photo: "/images/products/product-12.jpg",
    id: 3,
    created: sub(new Date(), { days: 8, hours: 6, minutes: 20 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'CeraVe Foaming Facial Cleanser',
    price: 43.02,
    discount: 15,
    related: true,
    salesPrice: 60.02,
    category: ['electronics'],
    gender: 'Men',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#1890FF', '#94D82D', '#FFC107'],
    photo: "/images/products/product-13.jpg",
    id: 4,
    created: sub(new Date(), { days: 4, hours: 9, minutes: 40 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'CeraVe ',
    price: 56.30,
    discount: 96.30,
    related: true,
    salesPrice: 900,
    category: ['fashion', 'electronics'],
    gender: 'Women',
    rating: 3,
    stock: false,
    qty: 1,
    colors: ['#00AB55', '#000000'],
    photo: "/images/products/product-14.jpg",
    id: 5,
    created: sub(new Date(), { days: 2, hours: 5, minutes: 50 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'Loretta Gentle Cleanser',
    price: 25.02,
    discount: 6,
    related: true,
    salesPrice: 30.00,
    category: ['electronics'],
    gender: 'Men',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#FFC0CB', '#FF4842'],
    photo: "/images/products/product-15.jpg",
    id: 6,
    created: sub(new Date(), { days: 2, hours: 9, minutes: 45 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'Eve Lom Cleanser',
    price: 45.20,
    discount: 50,
    related: false,
    salesPrice: 50.30,
    category: ['fashion'],
    gender: 'Women',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#FF4842', '#1890FF', '#94D82D'],
    photo: "/images/products/product-16.jpg",
    id: 7,
    created: sub(new Date(), { days: 6, hours: 10, minutes: 0 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'Neutrogena Deep Clean',
    price: 12.00,
    discount: 80,
    related: false,
    salesPrice: 15.00,
    category: ['fashion', 'toys'],
    gender: 'Women',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#1890FF', '#94D82D', '#FFC107'],
    photo: "/images/products/product-17.jpg",
    id: 8,
    created: sub(new Date(), { days: 7, hours: 5, minutes: 20 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'Neutrogena Oil-Free Acne',
    price: 17.15,
    discount: 25,
    related: false,
    salesPrice: 20.30,
    category: ['fashion'],
    gender: 'Women',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#00AB55', '#000000'],
    photo: '/images/products/product-18.jpg',
    id: 9,
    created: sub(new Date(), { days: 8, hours: 6, minutes: 20 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'EltaMD Foaming Facial',
    price: 45.20,
    discount: 40,
    related: false,
    salesPrice: 50.00,
    category: ['toys'],
    gender: 'Kids',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#FFC0CB', '#FF4842'],
    photo: "/images/products/product-19.jpg",
    id: 10,
    created: sub(new Date(), { days: 6, hours: 6, minutes: 20 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'Ultra Gentle Hydrating',
    price: 96.00,
    discount: 60,
    related: false,
    salesPrice: 112.00,
    category: ['toys'],
    gender: 'Kids',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#FF4842', '#1890FF', '#94D82D'],
    photo: "/images/products/product-20.jpg",
    id: 11,
    created: sub(new Date(), { days: 1, hours: 6, minutes: 20 }),
    description: chance.paragraph({ sentences: 2 }),
  },
  {
    title: 'The Ordinary',
    price: 12.00,
    discount: 5,
    related: false,
    salesPrice: 15.00,
    category: ['toys'],
    gender: 'Kids',
    rating: 3,
    stock: true,
    qty: 1,
    colors: ['#1890FF', '#94D82D', '#FFC107'],
    photo: "/images/products/product-21.jpg",
    id: 12,
    created: sub(new Date(), { days: 9, hours: 6, minutes: 20 }),
    description: chance.paragraph({ sentences: 2 }),
  },
];

mock.onGet('/api/data/eCommerce/ProductsDatav2').reply(() => {
  return [200, ProductsDatav2];
});

export default ProductsDatav2;
